Init
kaliberjs/sanity-image pull request #1
Opened 2021-12-01 21:36 UTC by peeke

Ik moet m nog testen, maar alvast een draft. Er zijn 3 specifieke usecases:

- `Image`: afbeelding met `height: auto`
- `ImageFixedAspectRatio`: afbeelding met een fixed height, gebaseerd op een aspect ratio (om het aantal crops onder controle te houden)
- `ImageCover`: afbeelding met `height: auto`, en `object-fit: cover`. De height is hierbij variabel. Hiervoor kan niet `Image` gebruikt worden, omdat de bereking voor je `sizes` attribuut anders is, omdat je afbeelding in sommige gevallen wordt opgeblazen.

2021-12-02 19:17 UTC, EECOLOR requested changes

2021-12-02 19:17 UTC, EECOLOR commented on src/Image.js
> +        : SIZES.map(x => ({ src: builder.image(image).width(x).quality(75).auto('format').url(), width: x }))
```suggestion
      const baseImage = builder.image(image).width(x).quality(75).auto('format')
      const sources = SIZES.map(width => ({ src: adjustImageRef.current(baseImage, width).url(), width }))
```

En dan waar je em gebruikt:

```
useSrcSet({ config, image, adjustImage: (image, width) => image.height(Math.round(x / aspectRatio)) })
```

2021-12-02 19:17 UTC, EECOLOR commented on src/Image.js
> +}
Ik zou hier nog een base class voor maken waarbij je de properties die verschillen meegeeft. Het basis mechanisme van `useSrcSet` en `sizes` is hetzelfde en ik denk dat dat duidelijk maakt wat nou precies het verschil tussen de 3 is (ik kan het mis hebben).

2021-12-10 08:14 UTC, peeke commented
`ImageFixedAspectRatio` is gerenamed naar `ImageCropped`

2021-12-10 08:45 UTC, EECOLOR requested changes
In de basis goed, paar kleine wijzigingen.

Misschien wel goed om een paar examples neer te zetten.

2021-12-10 08:45 UTC, EECOLOR commented on src/Image.js
> +      {...{ sanityConfig, image, layoutClassName }}
```suggestion
      {...{ sanityConfig, image, layoutClassName, imgProps }}
```

2021-12-10 08:45 UTC, EECOLOR commented on src/Image.js
> +      {...{ sanityConfig, image, layoutClassName }}
```suggestion
      {...{ sanityConfig, image, layoutClassName, imgProps }}
```

2021-12-10 08:45 UTC, EECOLOR commented on src/Image.js
> +}
```suggestion
}

```

2021-12-10 08:45 UTC, EECOLOR commented on src/Image.js
> +    const sizes = (naturalSize.height && displaySize.height && displaySize.width)
```suggestion
    const size = (naturalSize.height && displaySize.height && displaySize.width) 
```

2021-12-10 13:40 UTC, merged